apiVersion: v1
kind: Secret
metadata:
  name: bonny-secrets
type: Opaque
data:
  bonnyci-github-integration.key: <base64encoded key>
  gerrithub-ssh-key: <base64encoded key>
  gerrithub-ssh-key.pub: <base64encoded key>
---
apiVersion: v1
kind: Secret
metadata:
  name: nodepool-ssh-public
type: Opaque
data:
  authorized-keys: <base64encoded authorized_keys>
---
apiVersion: v1
kind: Secret
metadata:
  name: nodepool-ssh-private
type: Opaque
data:
  id_rsa: <base64encoded private ssh key>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bonny-log-server
data:
  known_hosts: |-
    logs.opentechsjc.bonnyci.org ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDM7tV7He/uofAwgYpkpKLuc+AN4z+HM9yUrs0V0ELhhCYZrTqeA940U46KItEgJK3/7xJQTlhh//erOmUVumOx8Grhpuvzru5wypOlXuCemYtbBrAIRrzmY0+oYgG7OLXqKMApuLr5UKGMjC4+dw4mD0VnmUBScUHypzrDgFEN8TMAaXNu1+ciju20yF7uGeQEZUiP5GKaIIj0ko+FAN6fK1a5JURX8xNrVOjqKxfl1ZLODfuT5K54pUDWf96+nho98k22PG21zLHK86e0aYraE4H5OiHK3993NeQc5Xos+j+T9ZnAcPdQxZmGh2HobBhKRejdY+IdYy+KSxSBamMd
    logs.opentechsjc.bonnyci.org ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKG/3CNoVJMurPBVjFraKczrtZJdjav54o1xoXcr0bZ3GoA2tyt0xGVof05q0mu8ihYFDB3BBTWCDfMDSPp1KSw=
    logs.opentechsjc.bonnyci.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDHq1HdEXrglpEp68DNBbpgzqsYDHLBXiPyFeWFgyzuD
