{{- if .Values.scheduler.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ printf "zuul-sched-%s" .Release.Name | trunc 24 }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
        component: zuul-scheduler
    spec:
      containers:
        - name: zuul-scheduler
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 4730
            - containerPort: {{ .Values.scheduler.webappPort }}
          command:
            - /usr/bin/supervisord
            - -c
            - /etc/supervisord-sched.conf

          # command:
          #   - zuul-scheduler
          #   - -d
          #   - -c
          #   - /etc/zuul/zuul.conf

          volumeMounts:
            - name: zuul-config-volume
              mountPath: /etc/zuul
            - name: zuul-tenant-volume
              mountPath: {{ .Values.tenants.mountPath }}
{{- if .Values.scheduler.volumeMounts }}
{{ toYaml .Values.scheduler.volumeMounts | indent 12 }}
{{- end }}

{{- if .Values.scheduler.resources }}
          resources:
{{ toYaml .Values.scheduler.resources | indent 12 }}
{{- end }}

{{- if .Values.scheduler.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.scheduler.nodeSelector | indent 8 }}
{{- end }}

      volumes:
        - name: zuul-config-volume
          configMap:
            name: {{ printf "zuul-config-%s" .Release.Name | trunc 24 }}

        - name: zuul-tenant-volume
{{- if .Values.tenants.data }}
          configMap:
            name: {{ printf "zuul-tenant-%s" .Release.Name | trunc 24 }}
{{- else if .Values.tenants.volume }}
{{ toYaml .Values.tenants.volume | indent 10 }}
{{- else }}
          emptyDir: {}
{{- end }}
{{- if .Values.scheduler.volumes }}
{{ toYaml .Values.scheduler.volumes | indent 8 }}
{{- end }}
{{- end }}
