{{- if .Values.launcher.enabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ printf "npl-launcher-%s" .Release.Name | trunc 24 }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.launcher.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: "nodepool-launcher"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          command:
            - nodepool-launcher
            - -d
            - -c
            - /etc/nodepool/nodepool.yaml
            - -l
            - /etc/nodepool/logging.yaml
          volumeMounts:
            - name: nodepool-config-volume
              mountPath: /etc/nodepool
            - name: nodepool-clouds-yaml
              mountPath: /etc/openstack
{{- if .Values.launcher.volumeMounts }}
{{ toYaml .Values.launcher.volumeMounts | indent 12 }}
{{- end }}

      volumes:
        - name: nodepool-config-volume
          configMap:
            name: {{ printf "nodepool-config-%s" .Release.Name | trunc 24 }}

        - name: nodepool-clouds-yaml
          secret:
            secretName: "{{ .Values.cloudsYamlSecret }}"

{{- if .Values.launcher.volumes }}
{{ toYaml .Values.launcher.volumes | indent 8 }}
{{- end }}
{{- end }}
